### ISSUE TITLE
Another documentation change request

### ISSUE THREAD

**Issue by Spudley** [nafiesl/SimpleCrudGenerator#10]
Hi.

Another request for documentation improvements.

The API section in the readme file is quite lacking. It would be very helpful, for example, to have a section describing what API commands are generated and how to call them.   :smile:

**Comment by Spudley** [comment]
I added some example code to the readme for how to use the API, and submitted it as a pull request. Could definitely do with more, but that makes a good start, I think.  :smile:

And thank you for writing this repo; it's been fun getting to know it.

**Comment by nafiesl** [comment]
Thank you very much. You are welcome to add more detail in this repo documentation. Your PR really helped me. 😁
