### ISSUE TITLE
Error installing browser kit in Laravel 5.8

### ISSUE THREAD

**Issue by christophervistal25** [nafiesl/SimpleCrudGenerator#14]

**Comment by nafiesl** [comment]
Please explain more detail.

**Comment by christophervistal25** [comment]
I'm trying to install the package Laravel 5.8 but it throws an error while installing the browser kit
then I figured out that it needs to downgrade the phpunit version to 6.0
anyways I solved the problem.

**Comment by christophervistal25** [comment]
I'm trying to install the package Laravel 5.8 but it throws an error while installing the browser kit
then I figured out that it needs to downgrade the phpunit version to 6.0
anyways I solved the problem.
