### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by novakben** [nafiesl/SimpleCrudGenerator#19]
Hey!
Cant be installed in Laravel 6 :/

**Comment by nafiesl** [comment]
Hi @novakben, you may try this for laravel 6 installation.
```
$ composer require symfony/css-selector:^4.0
$ composer require luthfi/simple-crud-generator --dev
```
Referring to this issue https://github.com/nafiesl/SimpleCrudGenerator/issues/17#issuecomment-569461882, it should work.
