### ISSUE TITLE
Error install di laravel 5.8 dengan php 7.4

### ISSUE THREAD

**Issue by orcome** [nafiesl/SimpleCrudGenerator#23]
Menjalankan perintah :
$ composer require luthfi/simple-crud-generator --dev

Muncul Pesan Error :

$ composer require luthfi/simple-crud-generator --dev
    1/4:	http://repo.packagist.org/p/provider-latest$6ba87fb526bea9f7e6714fcd485f29f3d59133a1f363432a124c54f7911ada4f.json
    2/4:	http://repo.packagist.org/p/provider-2020-04$bd384b515c1db87bdb3add737da96a699f7426e68dcc36f7446670b6d75aede9.json
    3/4:	http://repo.packagist.org/p/provider-2020-07$15c64024d2b1d55e2e2805f2ebee7f09285f9e73675a9d3538b73e08956ed75e.json
    4/4:	http://repo.packagist.org/p/provider-2019$6ca31841dae1837c5a8ba60c1f123f9b5cdb61ea1ce294d71e30d1d9727a08fb.json
    Finished: success: 4, skipped: 0, failure: 0, total: 4
Using version ^1.4 for luthfi/simple-crud-generator
./composer.json has been updated
    1/1:	http://repo.packagist.org/p/provider-latest$95f49b0b807cf02df3057ca045b3346e1eeecf2f89fd70811695a5d00f3e70f2.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.8.38
    - Conclusion: don't install laravel/framework v5.8.38
    - laravel/browser-kit-testing v5.0.0 requires illuminate/database ~5.7.0 -> satisfiable by illuminate/database[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - laravel/browser-kit-testing 6.x-dev requires illuminate/database ^7.0|^8.0 -> satisfiable by illuminate/database[7.x-dev, 8.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.28.0, v7.28.1, v7.28.2, v7.28.3, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.1.0, v8.2.0, v8.3.0, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.7.1].
    - laravel/browser-kit-testing v6.0.0 requires illuminate/database ^7.0 -> satisfiable by illuminate/database[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.28.0, v7.28.1, v7.28.2, v7.28.3, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - laravel/browser-kit-testing v6.1.0 requires illuminate/database ^7.0|^8.0 -> satisfiable by illuminate/database[7.x-dev, 8.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.28.0, v7.28.1, v7.28.2, v7.28.3, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.1.0, v8.2.0, v8.3.0, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.7.1].
    - don't install illuminate/database 5.7.17|don't install laravel/framework v5.8.38
    - don't install illuminate/database 5.7.18|don't install laravel/framework v5.8.38
    - don't install illuminate/database 5.7.19|don't install laravel/framework v5.8.38
    - don't install illuminate/database 5.7.x-dev|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.10|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.11|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.15|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.2|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.20|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.21|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.22|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.23|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.26|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.27|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.28|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.3|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.4|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.5|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.6|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.7|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.8|don't install laravel/framework v5.8.38
    - don't install illuminate/database v5.7.9|don't install laravel/framework v5.8.38
    - don't install illuminate/database 7.x-dev|don't install laravel/framework v5.8.38
    - don't install illuminate/database 8.x-dev|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.0.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.0.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.0.2|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.0.3|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.0.4|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.0.5|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.0.6|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.0.7|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.0.8|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.1.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.1.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.1.2|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.1.3|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.10.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.10.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.10.2|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.10.3|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.11.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.12.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.13.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.14.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.14.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.15.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.16.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.16.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.17.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.17.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.17.2|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.18.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.19.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.19.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.2.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.2.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.2.2|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.20.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.21.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.22.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.22.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.22.2|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.22.3|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.22.4|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.23.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.23.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.23.2|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.24.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.25.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.26.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.26.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.27.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.28.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.28.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.28.2|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.28.3|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.3.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.4.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.5.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.5.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.5.2|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.6.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.6.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.6.2|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.7.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.7.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.8.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.8.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.9.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.9.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v7.9.2|don't install laravel/framework v5.8.38
    - don't install illuminate/database v8.0.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v8.0.1|don't install laravel/framework v5.8.38
    - don't install illuminate/database v8.0.2|don't install laravel/framework v5.8.38
    - don't install illuminate/database v8.0.3|don't install laravel/framework v5.8.38
    - don't install illuminate/database v8.0.4|don't install laravel/framework v5.8.38
    - don't install illuminate/database v8.1.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v8.2.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v8.3.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v8.4.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v8.5.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v8.6.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v8.7.0|don't install laravel/framework v5.8.38
    - don't install illuminate/database v8.7.1|don't install laravel/framework v5.8.38
    - Installation request for laravel/framework (locked at v5.8.38, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.38].
    - Installation request for luthfi/simple-crud-generator ^1.4 -> satisfiable by luthfi/simple-crud-generator[1.4.0].
    - Conclusion: don't install symfony/css-selector v5.1.6|install laravel/browser-kit-testing 6.x-dev|install laravel/browser-kit-testing v5.0.0|install laravel/browser-kit-testing v6.0.0|install laravel/browser-kit-testing v6.1.0
    - Conclusion: remove symfony/css-selector v5.1.6|install laravel/browser-kit-testing 6.x-dev|install laravel/browser-kit-testing v5.0.0|install laravel/browser-kit-testing v6.0.0|install laravel/browser-kit-testing v6.1.0
    - luthfi/simple-crud-generator 1.4.0 requires laravel/browser-kit-testing ^5.0||^6.0 -> satisfiable by laravel/browser-kit-testing[5.0.x-dev, 6.x-dev, v5.0.0, v5.1.0, v5.1.1, v5.1.2, v5.1.3, v5.1.4, v6.0.0, v6.1.0].
    - laravel/browser-kit-testing 5.0.x-dev requires symfony/css-selector ^4.2 -> satisfiable by symfony/css-selector[4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9].
    - laravel/browser-kit-testing v5.1.0 requires symfony/css-selector ^4.2 -> satisfiable by symfony/css-selector[4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9].
    - laravel/browser-kit-testing v5.1.1 requires symfony/css-selector ^4.2 -> satisfiable by symfony/css-selector[4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9].
    - laravel/browser-kit-testing v5.1.2 requires symfony/css-selector ^4.2 -> satisfiable by symfony/css-selector[4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9].
    - laravel/browser-kit-testing v5.1.3 requires symfony/css-selector ^4.2 -> satisfiable by symfony/css-selector[4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9].
    - laravel/browser-kit-testing v5.1.4 requires symfony/css-selector ^4.2 -> satisfiable by symfony/css-selector[4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9].
    - Can only install one of: symfony/css-selector[4.2.x-dev, v5.1.6].
    - Can only install one of: symfony/css-selector[4.3.x-dev, v5.1.6].
    - Can only install one of: symfony/css-selector[4.4.x-dev, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.0, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.0-BETA1, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.0-BETA2, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.0-RC1, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.1, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.10, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.11, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.12, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.2, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.3, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.4, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.5, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.6, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.7, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.8, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.2.9, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.0, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.0-BETA1, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.0-BETA2, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.0-RC1, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.1, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.10, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.11, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.2, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.3, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.4, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.5, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.6, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.7, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.8, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.3.9, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.0, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.0-BETA1, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.0-BETA2, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.0-RC1, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.1, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.10, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.11, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.12, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.13, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.14, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.2, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.3, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.4, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.5, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.6, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.7, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.8, v5.1.6].
    - Can only install one of: symfony/css-selector[v4.4.9, v5.1.6].
    - Installation request for symfony/css-selector (locked at v5.1.6) -> satisfiable by symfony/css-selector[v5.1.6].

Installation failed, reverting ./composer.json to its original content.

![Selection_009](https://user-images.githubusercontent.com/43192211/94878828-22782400-0491-11eb-98a4-133075ed89eb.jpg)

**Comment by nafiesl** [comment]
mas @orcome, ternyata issuenya karena package `symfony/dom-crawler` terinstall versi `^5.0`, sedangkan yang cocok untuk browserkit test nya adalah versi `^4.0`.

Setelah saya coba solusi ini https://github.com/nafiesl/SimpleCrudGenerator/issues/17#issuecomment-569461882, package berhasil terinstall. 
```
$ composer require symfony/css-selector:^4.0
$ composer require luthfi/simple-crud-generator --dev
```

Ini log terminal saya barusan.
```
[10:40:40] ➜ 58_php74 (master)
$ composer require symfony/css-selector:^4.0
    1/3:	http://repo.packagist.org/p/provider-latest$b7985c6cb482a3dfe776b969d8488aa792b0981c6e3a726ab07fce74ccf46050.json
    2/3:	http://repo.packagist.org/p/provider-2020-04$1a53f08d234a48544fc6ec0fd3c818c455303e1b75dddbee1a2cf5493c6e1a97.json
    3/3:	http://repo.packagist.org/p/provider-2020-07$05e06d677ca2055584268e115605f64f727ac3e747428000945b630407c171f9.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downgrading symfony/css-selector (v5.1.6 => v4.4.14): Loading from cache
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
37 packages you are using are looking for funding.
Use the composer fund command to find out more!

[10:42:38] ➜ 58_php74 (master)
$ composer require luthfi/simple-crud-generator --dev
Using version ^1.4 for luthfi/simple-crud-generator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/1:	https://codeload.github.com/symfony/dom-crawler/legacy.zip/69690afed0881bb53f85dc1637e6b85416a1cd33
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Package operations: 3 installs, 0 updates, 0 removals
  - Installing symfony/dom-crawler (v4.4.14): Loading from cache
  - Installing laravel/browser-kit-testing (v5.1.4): Loading from cache
  - Installing luthfi/simple-crud-generator (1.4.0): Loading from cache
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: luthfi/simple-crud-generator
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
38 packages you are using are looking for funding.
Use the composer fund command to find out more!

[10:43:17] ➜ 58_php74 (master)
$ 
```

**Comment by orcome** [comment]
Ok terima kasih informasinya mas @nafiesl, sangat membantu ^_^
