### ISSUE TITLE
Don't override model

### ISSUE THREAD

**Issue by rabol** [nafiesl/SimpleCrudGenerator#33]
Would be cool to be able to generate crud for exiting models e.g. if the model file exists, just 'skip' generating

**Comment by nafiesl** [comment]
Hello @rabol, I think this is related to #24.

Currently, we have a confirmation question to generate CRUD files for the existing model.

![image](https://user-images.githubusercontent.com/8721551/111033586-ecca6480-844c-11eb-83f2-a45659e9bbf2.png)

**Comment by rabol** [comment]
Yes, I have seen, but if you say, no, then nothing is created

**Comment by nafiesl** [comment]
Correct @rabol, that is expected.

Do you have any suggestion if we answering "no", @rabol?

**Comment by rabol** [comment]
well, how do I then create CRUD for existing Models ?

**Comment by nafiesl** [comment]
Aha, I got your point now. So what is currently happening:

Current behavior:
1. let say we have an existing Invoice model.
2. We run the make:crud command for that model.
3. The package will ask if we want to create CRUD scaffolds for an existing model.
4. If we answer "yes", the package will replace all of the existing Invoice model content.

Expected behavior:
4. After we answer "yes", just create the scaffolds, don't touch the existing Invoice model class.

Correct, @rabol?

**Comment by rabol** [comment]
yes, only 'override' existing files if --force is specified on the command line, like many other artisan commands, please

**Comment by nafiesl** [comment]
Gotcha, nice catch @rabol, thanks for reporting this issue. I will work on the fix.

**Comment by nafiesl** [comment]
@rabol, FYI, this is a draft PR for fixing the class overrides issue #35.

**Comment by rabol** [comment]
I just installed the new version 2.2.1 - still the same behaviour

```
php artisan make:crud Test
```

Crud is generated

2nd time
```
php artisan make:crud Test
```
It ask, and if I say No, nothing happens

**Comment by nafiesl** [comment]
@rabol it's still expected. Try to answer "yes", it will create crud files without overriding your existing model.

**Comment by rabol** [comment]
Aha, got it.

Only one small thing: It create a new migration file

**Comment by nafiesl** [comment]
> Only one small thing: It create a new migration file

@rabol regarding this one, I can make another PR for asking "Do you need to create a migration file for the existing model? (yes/no)".

Maybe for another release. :+1:
