### ISSUE TITLE
Bootstrap 5 Support

### ISSUE THREAD

**Issue by nafiesl** [nafiesl/SimpleCrudGenerator#52]
## Goal

On our view stubs, currently we only have bootstrap versions 3 and 4 available. Since [laravel/ui:3.4.x](https://github.com/laravel/ui/releases/tag/v3.4.0), it uses bootstrap 5. So in order to use this package for the latest laravel and laravel/ui version, we need to add new view stubs for bootstrap 5.

## Checklist

Here are some view stubs that need to be checked and adjust:

- [x] full/create.stub
- [x] full/edit.stub
- [x] full/index.stub
- [x] full/show.stub
- [x] simple/forms.stub
- [x] simple/index.stub

## Notes

1. We might need to support bootstrap 4, so all those stub files need to be renamed
    - The existing `full/create.stub` into `full/create-bs4.stub`
    - The existing `full/edit.stub` into `full/edit-bs4.stub`, and so on.
2. Create those view stub files (no need `-bs5` suffix), since it will be used by default.
3. Bootstrap migration reference: https://getbootstrap.com/docs/5.2/migration

**Comment by orcome** [comment]
## Understood
- Duplicate the file full/create and rename the file to full/create-bs4, and also the next file.
- After duplicate to -bs4 then we adjust the full/create file using bootstrap 5 (filename does not need to be updated using additional -bs5), and also the next file.

**Comment by aryawiratama11** [comment]
SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "FROM"
LINE 1: SHOW COLUMNS FROM menu , when i use database postgresql

**Comment by nafiesl** [comment]
### Current progress

1. Duplicate the existing view stub files into -bs4 suffix
1. Update Full CRUD view files to support bootstrap 5
1. Update Simple CRUD view files to support bootstrap 5
1. Update Full CRUD with FormField view files to support bootstrap 5
1. Update Simple CRUD with FormField view files to support bootstrap 5
1. Add command option --bs4
1. Add command option --bs5
1. Make sure bootstrap 5 is the default template
2. PR #53 is ready for review.
