### ISSUE TITLE
Future Laravel 10.X Issue

### ISSUE THREAD

**Issue by moedayraki** [nafiesl/SimpleCrudGenerator#58]
I was playing around with the new Laravel 10 and wanted to install the SimpleCrudGenerator.

I got this error.

```bash
***** % composer require luthfi/simple-crud-generator:^3.0 --dev
./composer.json has been updated
Running composer update luthfi/simple-crud-generator
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires luthfi/simple-crud-generator ^3.0 -> satisfiable by luthfi/simple-crud-generator[3.0.0].
    - luthfi/simple-crud-generator 3.0.0 requires illuminate/support ^9.0 -> found illuminate/support[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by nafiesl** [comment]
Hi, @moedayraki thanks for testing this package on Laravel 10. Yes, currently we haven't added support for Laravel 10 yet, and we will. Currently, we still working on the Bootstrap 5 support (PR https://github.com/nafiesl/SimpleCrudGenerator/pull/53).

If you or someone can help to add support for Laravel 10, that would be very helpful. Else, we will work on it ASAP.

Thanks.

**Comment by moedayraki** [comment]
I've submitted a pull request to add support for Laravel 10. Please review and see if it'll work.

**Comment by nafiesl** [comment]
OK, I found the PR link https://github.com/nafiesl/SimpleCrudGenerator/pull/59

I will review this as soon as possible. Thanks a lot, @moedayraki!

**Comment by nafiesl** [comment]
Hello, @moedayraki. Thank you for our PR #59, as I mentioned in the comment, I apologize because I forgot about your PR #59. I have created a PR for laravel 10 support here: #62, and it has been merged.

We have added a new tag: [4.0.0](https://github.com/nafiesl/SimpleCrudGenerator/releases/tag/4.0.0).

Once again, I am sorry and appreciate your PR, thank you very much. We can close this issue now.
