### ISSUE TITLE
Undefined method firstItem()

### ISSUE THREAD

**Issue by Spudley** [nafiesl/SimpleCrudGenerator#8]
Hi.

Still having trouble getting up and running. I have managed to run SimpleCrudGenerator to create a Crud page.

* Create new Laravel 5.7 app.
* `composer require luthfi/simple-crud-generator --dev`
* `artisan make:crud ModelName`
* `artisan make:auth`  <-- <sub>(suggestion: make this more explicit in the docs as it doesn't work without this)</sub>
* `artisan migrate`
* Navigate to localhost/model_name

I successfully get a list view for my Crud, and can successfully create a record. However once I have created a record returning to the list page gives me an exception:

    Call to undefined method App\ModelName::firstItem()

I only get this issue for Crud forms created using `make:crud`. I do not get this problem if I do `make:crud-simple` instead.

Thank you.

**Comment by nafiesl** [comment]
I see, about the documentation, i will update the readme as soon as i can, and be more explicit for the package setup on fresh install laravel.

About the undefined fistItem() method problem, in the controller@index method, are you changing paginate() to.get() on the model database query?
Because firstItem() only works on paginated query results.

However, i will simulate to install the package from fresh install laravel 5.7. And get back to you after that, i will see if i found same problem like you did.

**Comment by Spudley** [comment]
Hi.

> About the undefined fistItem() method problem, in the controller@index method, are you changing paginate() to.get() on the model database query?

No, I didn't make any code modifications at all.

The only file I edited at all was the .env file to configure it use sqlite for the DB.

**Comment by nafiesl** [comment]
Can you please share/screenshot of the error page, the code on the view, and your controller@index method?

**Comment by Spudley** [comment]
Screenshot:

![screen shot 2018-11-21 at 09 36 46](https://user-images.githubusercontent.com/1370806/48832524-3e78ed80-ed71-11e8-8330-d99141e01e7d.png)

Code from the view:

````
@extends('layouts.app')

@section('title', __('form_submissions.list'))

@section('content')
<div class="mb-3">
    <div class="float-right">
        @can('create', new App\FormSubmissions)
            <a href="{{ route('form_submissions.create') }}" class="btn btn-success">{{ __('form_submissions.create') }}</a>
        @endcan
    </div>
    <h1 class="page-title">{{ __('form_submissions.list') }} <small>{{ __('app.total') }} : {{ $formSubmissions->total() }} {{ __('form_submissions.form_submissions') }}</small></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <form method="GET" action="" accept-charset="UTF-8" class="form-inline">
                    <div class="form-group">
                        <label for="q" class="control-label">{{ __('form_submissions.search') }}</label>
                        <input placeholder="{{ __('form_submissions.search_text') }}" name="q" type="text" id="q" class="form-control mx-sm-2" value="{{ request('q') }}">
                    </div>
                    <input type="submit" value="{{ __('form_submissions.search') }}" class="btn btn-secondary">
                    <a href="{{ route('form_submissions.index') }}" class="btn btn-link">{{ __('app.reset') }}</a>
                </form>
            </div>
            <table class="table table-sm table-responsive-sm">
                <thead>
                    <tr>
                        <th class="text-center">{{ __('app.table_no') }}</th>
                        <th>{{ __('form_submissions.name') }}</th>
                        <th>{{ __('form_submissions.description') }}</th>
                        <th class="text-center">{{ __('app.action') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($formSubmissions as $key => $formSubmissions)
                    <tr>
                        <td class="text-center">{{ $formSubmissions->firstItem() + $key }}</td>
                        <td>{!! $formSubmissions->name_link !!}</td>
                        <td>{{ $formSubmissions->description }}</td>
                        <td class="text-center">
                            @can('view', $formSubmissions)
                                <a href="{{ route('form_submissions.show', $formSubmissions) }}" id="show-form_submissions-{{ $formSubmissions->id }}">{{ __('app.show') }}</a>
                            @endcan
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="card-body">{{ $formSubmissions->appends(Request::except('page'))->render() }}</div>
        </div>
    </div>
</div>
@endsection
````

Controller@index method:

    /**
     * Display a listing of the formSubmissions.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $formSubmissionsQuery = FormSubmissions::query();
        $formSubmissionsQuery->where('name', 'like', '%'.request('q').'%');
        $formSubmissions = $formSubmissionsQuery->paginate(25);

        return view('form_submissions.index', compact('formSubmissions'));
    }

**Comment by nafiesl** [comment]
Oh, i see the problem there. You should use singular name of Model.

Try this command:
```
php artisan make:crud FormSubmission
```
instead of

```
php artisan make:crud FormSubmissions
```

**Comment by Spudley** [comment]
Ah! Okay.

And of course, the test I did with `crud-simple` had a singluar name, which is why it worked.

So I guess the takeaway from all this is something else that needs to be mentioned to the docs.  :)

(it could maybe also be handled more gracefully in the generator, but a sentence added to the docs would be a quicker way to fix it for now)

Thanks for your help.  :-)

**Comment by nafiesl** [comment]
Hehe, you were right, we should mention that on the docs, just to be more explicit. And I will also note your suggestion, the generator should detect the pluralized given model name, and covert it to singular.

You're welcome, yhanks a lot.
