### ISSUE TITLE
Generated API tests include reference to 'Vehicle'

### ISSUE THREAD

**Issue by Spudley** [nafiesl/SimpleCrudGenerator#9]
Another ticket  :-)

I have generated an API using the SimpleCrudGenerator. The API was named 'Submission'. I already had a simple crud form generated using the same name.

I ran /vendor/bin/phpunit, and got errors.

The errors were due to the test methods for the API containing references to a 'Vehicle' class. I had not created anything named 'Vehicle'.

I fixed it by doing a search and replace in the test file, replacing all instances of `Vehicle` with `Submission`. The test worked fine after this.

**Comment by nafiesl** [comment]
You are welcome to create PR to fix this too, if you dont mind.

**Comment by nafiesl** [comment]
Yes i do. Thanks a lot @Spudley.
